### ISSUE TITLE
Code for reconstructing event edges

### ISSUE THREAD

**Issue by Tobias-Fischer** [alexjunholee/EventVLAD#2]
Dear @alexjunholee, many thanks for this repository! As far as I can see, it only contains the NetVLAD part of your pipeline. Could you please make the code for reconstructing the event edges available as well?

Many thanks!

**Comment by alexjunholee** [comment]
Dear @Tobias-Fischer, Thanks for your attention, we've added the sample denoiser in the code.
Also, the pretrained weight for denoiser is also available.

Thanks!
Alex
